version: '3'

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: dvdrental
    ports:
      - 5432:5432
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d/
      - ./databases:/databases